name: Vault Action Trigger

on:
  workflow_dispatch:
    inputs:
      vault_id:
        description: 'Vault ID'
        required: true
        type: string
      action_type:
        description: 'Type of action (deposit or withdraw)'
        required: true
        type: choice
        options:
          - deposit
          - withdraw
      transaction_hash:
        description: 'Transaction hash'
        required: true
        type: string
      amount:
        description: 'Amount involved in the transaction'
        required: true
        type: string
      user_address:
        description: 'User wallet address'
        required: true
        type: string
      timestamp:
        description: 'Transaction timestamp'
        required: true
        type: string
      retry_count:
        description: 'Current retry count (internal use)'
        required: false
        type: string
        default: '0'
      original_timestamp:
        description: 'Original transaction timestamp (internal use)'
        required: false
        type: string

jobs:
  process-vault-action:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Process vault action
        run: |
          echo "Processing vault action:"
          echo "Vault ID: ${{ github.event.inputs.vault_id }}"
          echo "Action Type: ${{ github.event.inputs.action_type }}"
          echo "Transaction Hash: ${{ github.event.inputs.transaction_hash }}"
          echo "Amount: ${{ github.event.inputs.amount }}"
          echo "User Address: ${{ github.event.inputs.user_address }}"
          echo "Timestamp: ${{ github.event.inputs.timestamp }}"
          echo "Retry Count: ${{ github.event.inputs.retry_count }}"
          
          # Determine if this is a retry or the first run
          RETRY_COUNT="${{ github.event.inputs.retry_count }}"
          if [ "$RETRY_COUNT" = "0" ] || [ -z "$RETRY_COUNT" ]; then
            echo "🚀 First run - will trigger subgraph sync and schedule retries"
          else
            echo "🔄 Retry #$RETRY_COUNT - triggering subgraph sync"
          fi
          
      - name: Trigger subgraph sync
        run: |
          echo "Triggering subgraph sync for vault ${{ github.event.inputs.vault_id }}"
          
          # Map vault ID to workflow file
          VAULT_ID="${{ github.event.inputs.vault_id }}"
          case "$VAULT_ID" in
            "detrade-core-usdc"|"dev-detrade-core-usdc")
              WORKFLOW_FILE="sync-scheduler-usdc.yml"
              ;;
            "detrade-core-eth")
              WORKFLOW_FILE="sync-scheduler-eth.yml"
              ;;
            "detrade-core-eurc")
              WORKFLOW_FILE="sync-scheduler-eurc.yml"
              ;;
            *)
              echo "❌ Unknown vault ID: $VAULT_ID"
              exit 1
              ;;
          esac
          
          echo "📡 Triggering workflow: $WORKFLOW_FILE"
          
          # Trigger the subgraph sync workflow
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            "https://api.github.com/repos/detradefund/subgraph/actions/workflows/$WORKFLOW_FILE/dispatches" \
            -d "{\"ref\": \"master\", \"inputs\": {\"manual_trigger\": \"true\", \"source\": \"vault-action-retry-${{ github.event.inputs.retry_count }}\"}}"
          
          if [ $? -eq 0 ]; then
            echo "✅ Subgraph sync triggered successfully"
          else
            echo "❌ Failed to trigger subgraph sync"
          fi
          
      - name: Schedule retries (first run only)
        if: github.event.inputs.retry_count == '0' || github.event.inputs.retry_count == ''
        run: |
          echo "📅 Scheduling retry workflows..."
          
          # Original timestamp for tracking
          ORIGINAL_TIMESTAMP="${{ github.event.inputs.original_timestamp }}"
          if [ -z "$ORIGINAL_TIMESTAMP" ]; then
            ORIGINAL_TIMESTAMP="${{ github.event.inputs.timestamp }}"
          fi
          
          # Schedule retries with delays (3min, 10min, 30min, 1h, 3h)
          # We'll use GitHub Actions workflow_dispatch API with delays
          
          # Helper function to schedule a retry
          schedule_retry() {
            local delay_minutes=$1
            local retry_number=$2
            local delay_label=$3
            
            echo "⏰ Scheduling retry #$retry_number after $delay_label..."
            
            # Convert minutes to seconds
            local delay_seconds=$((delay_minutes * 60))
            
            # Schedule the retry using a background process
            (
              sleep $delay_seconds
              echo "🔄 Executing retry #$retry_number after $delay_label"
              
              curl -X POST \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                -H "Content-Type: application/json" \
                "https://api.github.com/repos/${{ github.repository }}/actions/workflows/vault-action-example.yml/dispatches" \
                -d "{
                  \"ref\": \"${{ github.ref_name }}\",
                  \"inputs\": {
                    \"vault_id\": \"${{ github.event.inputs.vault_id }}\",
                    \"action_type\": \"${{ github.event.inputs.action_type }}\",
                    \"transaction_hash\": \"${{ github.event.inputs.transaction_hash }}\",
                    \"amount\": \"${{ github.event.inputs.amount }}\",
                    \"user_address\": \"${{ github.event.inputs.user_address }}\",
                    \"timestamp\": \"${{ github.event.inputs.timestamp }}\",
                    \"retry_count\": \"$retry_number\",
                    \"original_timestamp\": \"$ORIGINAL_TIMESTAMP\"
                  }
                }"
              
              if [ $? -eq 0 ]; then
                echo "✅ Retry #$retry_number scheduled successfully"
              else
                echo "❌ Failed to schedule retry #$retry_number"
              fi
            ) &
          }
          
          # Schedule all retries
          schedule_retry 3 1 "3 minutes"
          schedule_retry 10 2 "10 minutes"  
          schedule_retry 30 3 "30 minutes"
          schedule_retry 60 4 "1 hour"
          schedule_retry 180 5 "3 hours"
          
          echo "🎯 All retries scheduled successfully!"
          echo "The workflow will re-trigger itself at:"
          echo "- 3 minutes from now"
          echo "- 10 minutes from now"
          echo "- 30 minutes from now"
          echo "- 1 hour from now"
          echo "- 3 hours from now"
          
      - name: Send notification
        if: github.event.inputs.action_type == 'deposit'
        run: |
          echo "Sending deposit notification for vault ${{ github.event.inputs.vault_id }}"
          # Add notification logic here
          
      - name: Update analytics
        run: |
          echo "Updating analytics for transaction ${{ github.event.inputs.transaction_hash }}"
          # Add analytics update logic here
          
      - name: Log action
        run: |
          echo "Action completed successfully"
          echo "Vault: ${{ github.event.inputs.vault_id }}"
          echo "Type: ${{ github.event.inputs.action_type }}"
          echo "Hash: ${{ github.event.inputs.transaction_hash }}"
          echo "Retry: ${{ github.event.inputs.retry_count }}"
          
          RETRY_COUNT="${{ github.event.inputs.retry_count }}"
          if [ "$RETRY_COUNT" = "0" ] || [ -z "$RETRY_COUNT" ]; then
            echo "🎉 First run completed - retries scheduled"
          else
            echo "🔄 Retry #$RETRY_COUNT completed"
          fi 