name: Vault Auto Scheduler

on:
  push:
    branches: [ master, main ]
  schedule:
    # Runs every 4 hours at minute 0
    - cron: '0 */4 * * *'
  workflow_dispatch:
    # Allow manual trigger

jobs:
  trigger-vault-actions:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Trigger vault actions for all vaults
        run: |
          echo "🚀 Starting automatic vault action triggers"
          
          # Get current timestamp
          CURRENT_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          
          # Define vault configurations
          declare -A VAULTS=(
            ["detrade-core-usdc"]="USDC Vault"
            ["detrade-core-eth"]="ETH Vault" 
            ["detrade-core-eurc"]="EURC Vault"
          )
          
          # Trigger vault-action-example.yml for each vault
          for VAULT_ID in "${!VAULTS[@]}"; do
            VAULT_NAME="${VAULTS[$VAULT_ID]}"
            echo "📡 Triggering vault action for $VAULT_NAME ($VAULT_ID)"
            
            # Trigger the vault-action-example workflow
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Content-Type: application/json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/workflows/vault-action-example.yml/dispatches" \
              -d "{
                \"ref\": \"${{ github.ref_name }}\",
                \"inputs\": {
                  \"vault_id\": \"$VAULT_ID\",
                  \"action_type\": \"deposit\",
                  \"transaction_hash\": \"auto-trigger-$(date +%s)-$VAULT_ID\",
                  \"amount\": \"0\",
                  \"user_address\": \"0x0000000000000000000000000000000000000000\",
                  \"timestamp\": \"$CURRENT_TIMESTAMP\"
                }
              }"
            
            if [ $? -eq 0 ]; then
              echo "✅ $VAULT_NAME trigger successful"
            else
              echo "❌ $VAULT_NAME trigger failed"
            fi
            
            # Small delay between triggers
            sleep 2
          done
          
          echo "🎉 All vault action triggers completed"
          
      - name: Log trigger event
        run: |
          echo "📊 Vault Auto Scheduler Summary:"
          echo "Triggered by: ${{ github.event_name }}"
          echo "Timestamp: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          echo "Ref: ${{ github.ref_name }}"
          echo "Vaults triggered: detrade-core-usdc, detrade-core-eth, detrade-core-eurc"
          
          if [ "${{ github.event_name }}" = "schedule" ]; then
            echo "🕐 Scheduled execution (every 4 hours)"
          elif [ "${{ github.event_name }}" = "push" ]; then
            echo "🔄 Triggered by code push"
          else
            echo "👤 Manual trigger"
          fi 